---
from: Fan Cheng
# fromqualifications: M.AppliedStat
fromtitle: Ph.D. student of Statistics
fromWWW: fancheng.me
fromemail: Fan.Cheng@monash.edu
fromphone: +61 466820666
fromsignature: Signature.jpg
toname: Tyler McCormick, Editor
toaddress: Journal of Computational and Graphical Statistics
opening: Dear Dr. McCormick,
closing: Kind regards,
spacing: 1.5
output: MonashEBSTemplates::letter
---

I am writing to submit my article entitled "Manifold learning with approximate nearest neighbors" co-authored with Rob J Hyndman, and Anastasios Panagiotelis for consideration of publication in the *Journal of Computational and Graphical Statistics*.

We believe that this manuscript is appropriate for publication by the *Journal of Computational and Graphical Statistics* because it explores and evaluates a broad range of approximate nearest neighbor methods within manifold learning algorithms and incorporates them into statistical manifolds.

We confirm that this manuscript is original and has not been previously published, nor is it currently under consideration by another journal. A preprint has been made available at arXiv and Monash EBS working paper series.

Thank you for your consideration of this manuscript.
